# ===============================
# 🚀 PERFORMANCE
# ===============================
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx2048m
org.gradle.daemon=true
org.gradle.parallel=true

# ===============================
# 📱 ANDROID
# ===============================
android.useAndroidX=true
android.enablePngCrunchInReleaseBuilds=true

# ===============================
# 🧠 ARCHITECTURE (CRASH FIX)
# ===============================
newArchEnabled=false

# ===============================
# ⚡ ENGINE
# ===============================
hermesEnabled=true

# ===============================
# 🎨 UI
# ===============================
edgeToEdgeEnabled=true

# ===============================
# 🖼️ MEDIA
# ===============================
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# ===============================
# 📦 PACKAGING
# ===============================
expo.useLegacyPackaging=false

# ===============================
# 🔧 DEV
# ===============================
EX_DEV_CLIENT_NETWORK_INSPECTOR=true
